export const SCOPENAME = 'module:tokens';

// info
export const GET_TOKEN_INFO = `${SCOPENAME}/GET_TOKEN_INFO`;
export const SET_TOKEN_INFO = `${SCOPENAME}/SET_TOKEN_INFO`;

// list
export const GET_TOKEN_LIST = `${SCOPENAME}/GET_TOKEN_LIST`;
export const GET_TOKEN_HOLDER_LIST = `${SCOPENAME}/GET_TOKEN_HOLDER_LIST`;
export const GET_TOKEN_TRANSACTION_LIST = `${SCOPENAME}/GET_TOKEN_TRANSACTION_LIST`;
export const SET_TOKEN_LIST = `${SCOPENAME}/SET_TOKEN_LIST`;
export const SET_TOKEN_HOLDER_LIST = `${SCOPENAME}/SET_TOKEN_HOLDER_LIST`;
export const SET_TOKEN_TRANSACTION_LIST = `${SCOPENAME}/SET_TOKEN_TRANSACTION_LIST`;
export const GET_TOKEN_LIST_REQUEST = `${SCOPENAME}/GET_TOKEN_LIST_REQUEST`;
export const GET_TOKEN_HOLDER_LIST_REQUEST = `${SCOPENAME}/GET_TOKEN_HOLDER_LIST_REQUEST`;
export const GET_TOKEN_TRANSACTION_LIST_REQUEST = `${SCOPENAME}/GET_TOKEN_TRANSACTION_LIST_REQUEST`;
export const GET_TOKEN_LIST_SUCCESS = `${SCOPENAME}/GET_TOKEN_LIST_SUCCESS`;
export const GET_TOKEN_LIST_FAILURE = `${SCOPENAME}/GET_TOKEN_LIST_FAILURE`;
export const GET_TOKEN_HOLDER_LIST_SUCCESS = `${SCOPENAME}/GET_TOKEN_HOLDER_LIST_SUCCESS`;
export const GET_TOKEN_HOLDER_LIST_FAILURE = `${SCOPENAME}/GET_TOKEN_HOLDER_LIST_FAILURE`;
export const GET_TOKEN_TRANSACTION_LIST_SUCCESS = `${SCOPENAME}/GET_TOKEN_TRANSACTION_LIST_SUCCESS`;
export const GET_TOKEN_TRANSACTION_LIST_FAILURE = `${SCOPENAME}/GET_TOKEN_TRANSACTION_LIST_FAILURE`;
export const GET_TOKEN_LIST_IN_DELAY = `${SCOPENAME}/GET_TOKEN_LIST_IN_DELAY`;
export const GET_TOKEN_HOLDER_LIST_IN_DELAY = `${SCOPENAME}/GET_TOKEN_HOLDER_LIST_IN_DELAY`;
export const GET_TOKEN_TRANSACTION_LIST_IN_DELAY = `${SCOPENAME}/GET_TOKEN_TRANSACTION_LIST_IN_DELAY`;
