export const SCOPENAME = 'module:tokens';

// info
export const GET_BLOCK = `${SCOPENAME}/GET_BLOCK`;
export const GET_UNCLE_BLOCK = `${SCOPENAME}/GET_UNCLE_BLOCK`;
export const GET_BLOCK_BY_HEIGHT = `${SCOPENAME}/GET_BLOCK_BY_HEIGHT`;
export const GET_UNCLE_BLOCK_BY_HEIGHT = `${SCOPENAME}/GET_UNCLE_BLOCK_BY_HEIGHT`;
export const SET_BLOCK = `${SCOPENAME}/SET_BLOCK`;
export const SET_UNCLE_BLOCK = `${SCOPENAME}/SET_UNCLE_BLOCK`;

// list
export const GET_BLOCK_LIST = `${SCOPENAME}/GET_BLOCK_LIST`;
export const GET_TOKEN_LIST = `${SCOPENAME}/GET_TOKEN_LIST`;
export const GET_UNCLE_BLOCK_LIST = `${SCOPENAME}/GET_UNCLE_BLOCK_LIST`;
export const SET_BLOCK_LIST = `${SCOPENAME}/SET_BLOCK_LIST`;
export const SET_TOKEN_LIST = `${SCOPENAME}/SET_TOKEN_LIST`;
export const SET_UNCLE_BLOCK_LIST = `${SCOPENAME}/SET_UNCLE_BLOCK_LIST`;
export const GET_BLOCK_LIST_REQUEST = `${SCOPENAME}/GET_BLOCK_LIST_REQUEST`;
export const GET_TOKEN_LIST_REQUEST = `${SCOPENAME}/GET_TOKEN_LIST_REQUEST`;
export const GET_UNCLE_BLOCK_LIST_REQUEST = `${SCOPENAME}/GET_UNCLE_BLOCK_LIST_REQUEST`;
export const GET_BLOCK_LIST_SUCCESS = `${SCOPENAME}/GET_BLOCK_LIST_SUCCESS`;
export const GET_BLOCK_LIST_FAILURE = `${SCOPENAME}/GET_BLOCK_LIST_FAILURE`;
export const GET_TOKEN_LIST_SUCCESS = `${SCOPENAME}/GET_TOKEN_LIST_SUCCESS`;
export const GET_TOKEN_LIST_FAILURE = `${SCOPENAME}/GET_TOKEN_LIST_FAILURE`;
export const GET_UNCLE_BLOCK_LIST_SUCCESS = `${SCOPENAME}/GET_UNCLE_BLOCK_LIST_SUCCESS`;
export const GET_UNCLE_BLOCK_LIST_FAILURE = `${SCOPENAME}/GET_UNCLE_BLOCK_LIST_FAILURE`;
export const GET_BLOCK_LIST_IN_DELAY = `${SCOPENAME}/GET_BLOCK_LIST_IN_DELAY`;
export const GET_TOKEN_LIST_IN_DELAY = `${SCOPENAME}/GET_TOKEN_LIST_IN_DELAY`;
export const GET_UNCLE_BLOCK_LIST_IN_DELAY = `${SCOPENAME}/GET_UNCLE_BLOCK_LIST_IN_DELAY`;
