apiVersion: apps/v1
kind: Deployment
metadata:
  name: starcoin-explorer-deployment
  namespace: starcoin-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starcoin-explorer
  template:
    metadata:
      labels:
        app: starcoin-explorer
    spec:
      containers:
        - name: react-app
          image: starcoin/starcoin_explorer:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: starcoin-explorer-service
  namespace: starcoin-client
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32000
  selector:
    app: starcoin-explorer