apiVersion: apps/v1
kind: Deployment
metadata:
  name: starcoin-explorer-deployment
  namespace: starcoin-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starcoin-client
  template:
    metadata:
      labels:
        app: starcoin-client
    spec:
      containers:
        - name: react-app
          image: starcoin_explorer:v1.9.10
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: starcoin-explorer
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: react-app