export const SCOPENAME = 'module:walletLogin';

export const GET_ACCOUNTS = `${SCOPENAME}/GET_ACCOUNTS`;

export const SET_ACCOUNTS = `${SCOPENAME}/SET_ACCOUNTS`;

export const SET_STATE = `${SCOPENAME}/SET_STATE`;

export const GET_STATE = `${SCOPENAME}/GET_STATE`;

export const GET_SIGNRESULT = `${SCOPENAME}/GET_SIGNRESULT`;

export const SET_BALANCE = `${SCOPENAME}/SET_BALANCE`;

export const GET_BALANCE = `${SCOPENAME}/GET_BALANCE`;

export const SET_SIGNRESULT = `${SCOPENAME}/SET_SIGNRESULT`;

export const GET_CHAINID = `${SCOPENAME}/GET_CHAINID`;

export const SET_PROVIDER = `${SCOPENAME}/SET_PROVIDER`;

export const GET_BALANCE_DELAY = `${SCOPENAME}/GET_BALANCE_DELAY`;

export const CONNECTWALLET = `${SCOPENAME}/CONNECTWALLET`;

export const WALLETINIT = `${SCOPENAME}/WALLETINIT`;

export const LOGOUT = `${SCOPENAME}/LOGOUT`;

export const SET_USERINFO = `${SCOPENAME}/SET_USERINFO`;

export const  SET_USERINFO_DATA = `${SCOPENAME}/SET_USERINFO_DATA`;

export const UPDATE_USERINFO = `${SCOPENAME}/CHANGE_USERINFO`;

export const DELETE_USERINFO = `${SCOPENAME}/DELETE_USERINFO`