export const SCOPENAME = 'module:blocks';

// info
export const GET_BLOCK = `${SCOPENAME}/GET_BLOCK`;
export const SET_BLOCK = `${SCOPENAME}/SET_BLOCK`;

// list
export const GET_BLOCK_LIST = `${SCOPENAME}/GET_BLOCK_LIST`;
export const SET_BLOCK_LIST = `${SCOPENAME}/SET_BLOCK_LIST`;
export const GET_BLOCK_LIST_REQUEST = `${SCOPENAME}/GET_BLOCK_LIST_REQUEST`;
export const GET_BLOCK_LIST_SUCCESS = `${SCOPENAME}/GET_BLOCK_LIST_SUCCESS`;
export const GET_BLOCK_LIST_FAILURE = `${SCOPENAME}/GET_BLOCK_LIST_FAILURE`;

