export const SCOPENAME = 'module:transactions';

// info
export const GET_TRANSACTION = `${SCOPENAME}/GET_TRANSACTION`;
export const SET_TRANSACTION = `${SCOPENAME}/SET_TRANSACTION`;

// list
export const GET_TRANSACTION_LIST = `${SCOPENAME}/GET_TRANSACTION_LIST`;
export const SET_TRANSACTION_LIST = `${SCOPENAME}/SET_TRANSACTION_LIST`;
export const GET_TRANSACTION_LIST_REQUEST = `${SCOPENAME}/GET_TRANSACTION_LIST_REQUEST`;
export const GET_TRANSACTION_LIST_SUCCESS = `${SCOPENAME}/GET_TRANSACTION_LIST_SUCCESS`;
export const GET_TRANSACTION_LIST_FAILURE = `${SCOPENAME}/GET_TRANSACTION_LIST_FAILURE`;

// Address Transactions
export const GET_ADDRESS_TRANSACTIONS = `${SCOPENAME}/GET_ADDRESS_TRANSACTIONS`;
export const SET_ADDRESS_TRANSACTIONS = `${SCOPENAME}/SET_ADDRESS_TRANSACTIONS`;

